python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='contrac' --model='lr' --epsilon=1.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='contrac' --model='lr' --epsilon=1.25
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='contrac' --model='lr' --epsilon=1.5
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='contrac' --model='lr' --epsilon=1.75
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='contrac' --model='lr' --epsilon=2.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='contrac' --model='lr' --epsilon=None
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='contrac' --model='rf' --epsilon=1.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='contrac' --model='rf' --epsilon=1.25
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='contrac' --model='rf' --epsilon=1.5
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='contrac' --model='rf' --epsilon=1.75
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='contrac' --model='rf' --epsilon=2.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='contrac' --model='rf' --epsilon=None
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ilpd' --model='lr' --epsilon=1.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ilpd' --model='lr' --epsilon=1.25
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ilpd' --model='lr' --epsilon=1.5
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ilpd' --model='lr' --epsilon=1.75
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ilpd' --model='lr' --epsilon=2.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ilpd' --model='lr' --epsilon=None
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ilpd' --model='rf' --epsilon=1.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ilpd' --model='rf' --epsilon=1.25
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ilpd' --model='rf' --epsilon=1.5
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ilpd' --model='rf' --epsilon=1.75
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ilpd' --model='rf' --epsilon=2.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ilpd' --model='rf' --epsilon=None
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='audiology' --model='lr' --epsilon=1.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='audiology' --model='lr' --epsilon=1.25
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='audiology' --model='lr' --epsilon=1.5
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='audiology' --model='lr' --epsilon=1.75
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='audiology' --model='lr' --epsilon=2.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='audiology' --model='lr' --epsilon=None
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='audiology' --model='rf' --epsilon=1.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='audiology' --model='rf' --epsilon=1.25
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='audiology' --model='rf' --epsilon=1.5
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='audiology' --model='rf' --epsilon=1.75
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='audiology' --model='rf' --epsilon=2.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='audiology' --model='rf' --epsilon=None
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ctg' --model='lr' --epsilon=1.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ctg' --model='lr' --epsilon=1.25
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ctg' --model='lr' --epsilon=1.5
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ctg' --model='lr' --epsilon=1.75
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ctg' --model='lr' --epsilon=2.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ctg' --model='lr' --epsilon=None
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ctg' --model='rf' --epsilon=1.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ctg' --model='rf' --epsilon=1.25
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ctg' --model='rf' --epsilon=1.5
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ctg' --model='rf' --epsilon=1.75
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ctg' --model='rf' --epsilon=2.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='ctg' --model='rf' --epsilon=None
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='mammo' --model='lr' --epsilon=1.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='mammo' --model='lr' --epsilon=1.25
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='mammo' --model='lr' --epsilon=1.5
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='mammo' --model='lr' --epsilon=1.75
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='mammo' --model='lr' --epsilon=2.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='mammo' --model='lr' --epsilon=None
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='mammo' --model='rf' --epsilon=1.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='mammo' --model='rf' --epsilon=1.25
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='mammo' --model='rf' --epsilon=1.5
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='mammo' --model='rf' --epsilon=1.75
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='mammo' --model='rf' --epsilon=2.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='mammo' --model='rf' --epsilon=None
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='dermatology' --model='lr' --epsilon=1.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='dermatology' --model='lr' --epsilon=1.25
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='dermatology' --model='lr' --epsilon=1.5
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='dermatology' --model='lr' --epsilon=1.75
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='dermatology' --model='lr' --epsilon=2.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='dermatology' --model='lr' --epsilon=None
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='dermatology' --model='rf' --epsilon=1.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='dermatology' --model='rf' --epsilon=1.25
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='dermatology' --model='rf' --epsilon=1.5
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='dermatology' --model='rf' --epsilon=1.75
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='dermatology' --model='rf' --epsilon=2.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='dermatology' --model='rf' --epsilon=None
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='german-credit' --model='lr' --epsilon=1.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='german-credit' --model='lr' --epsilon=1.25
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='german-credit' --model='lr' --epsilon=1.5
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='german-credit' --model='lr' --epsilon=1.75
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='german-credit' --model='lr' --epsilon=2.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='german-credit' --model='lr' --epsilon=None
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='german-credit' --model='rf' --epsilon=1.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='german-credit' --model='rf' --epsilon=1.25
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='german-credit' --model='rf' --epsilon=1.5
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='german-credit' --model='rf' --epsilon=1.75
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='german-credit' --model='rf' --epsilon=2.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='german-credit' --model='rf' --epsilon=None
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='credit-approval' --model='lr' --epsilon=1.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='credit-approval' --model='lr' --epsilon=1.25
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='credit-approval' --model='lr' --epsilon=1.5
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='credit-approval' --model='lr' --epsilon=1.75
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='credit-approval' --model='lr' --epsilon=2.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='credit-approval' --model='lr' --epsilon=None
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='credit-approval' --model='rf' --epsilon=1.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='credit-approval' --model='rf' --epsilon=1.25
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='credit-approval' --model='rf' --epsilon=1.5
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='credit-approval' --model='rf' --epsilon=1.75
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='credit-approval' --model='rf' --epsilon=2.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='credit-approval' --model='rf' --epsilon=None
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='bank' --model='lr' --epsilon=1.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='bank' --model='lr' --epsilon=1.25
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='bank' --model='lr' --epsilon=1.5
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='bank' --model='lr' --epsilon=1.75
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='bank' --model='lr' --epsilon=2.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='bank' --model='lr' --epsilon=None
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='bank' --model='rf' --epsilon=1.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='bank' --model='rf' --epsilon=1.25
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='bank' --model='rf' --epsilon=1.5
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='bank' --model='rf' --epsilon=1.75
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='bank' --model='rf' --epsilon=2.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='bank' --model='rf' --epsilon=None
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='adult' --model='lr' --epsilon=1.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='adult' --model='lr' --epsilon=1.25
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='adult' --model='lr' --epsilon=1.5
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='adult' --model='lr' --epsilon=1.75
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='adult' --model='lr' --epsilon=2.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='adult' --model='lr' --epsilon=None
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='adult' --model='rf' --epsilon=1.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='adult' --model='rf' --epsilon=1.25
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='adult' --model='rf' --epsilon=1.5
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='adult' --model='rf' --epsilon=1.75
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='adult' --model='rf' --epsilon=2.0
python exp/tabular_dp.py --num_models=100 --n_jobs=8 --dataset='adult' --model='rf' --epsilon=None
