program: poetry run python ext/Handcrafted-DP/cnns.py --dataset=cifar10 --use_scattering --batch_size=8192 --lr=4 --input_norm=BN --bn_noise_multiplier=8 --device=cuda:1
method: grid
parameters:
    noise_multiplier:
        values: [10.0, 8.0, 6.0, 5.0, 4.0]
    seed:
        max: 50
