program: python exp/tabular_dp.py --max_num_models=10000
method: grid
parameters:
    dataset:
        values:
        - credit-approval
    model:
        values:
        - lr
    epsilon:
        values: [10.0, 15.0, 20.0, 25.0, 30.0, 35.0, 40.0]
    num_models:
        value: 1000
