program: python exp/tabular_dp.py --condition=None
method: grid
parameters:
    dataset:
        values:
        - credit-approval
        - contrac
        - mammo
        - dermatology
    model:
        values:
        - lr
    epsilon:
        values: [0.50, 0.75, 1.00, 1.25, 1.50, 1.75, 2.00, 2.50, 3.00, 3.50, 4.00, 4.5, 5.0]
    num_models:
        value: 5000
